fix: se actualiza static web app deployv1

diff --git a/.github/workflows/azure-static-web-apps-polite-ocean-0a5354e10.yml b/.github/workflows/azure-static-web-apps-polite-ocean-0a5354e10.yml
--- a/.github/workflows/azure-static-web-apps-polite-ocean-0a5354e10.yml
+++ b/.github/workflows/azure-static-web-apps-polite-ocean-0a5354e10.yml
@@ -19,21 +19,26 @@ jobs:
     name: Build and Deploy Job
     steps:
       - uses: actions/checkout@v3
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
         with:
-          submodules: true
+          node-version: '18'
+      - name: Install Dependencies
+        run: |
+          npm install
+          npx update-browserslist-db@latest
+      - name: Audit Fix
+        run: npm audit fix || echo "Audit fix could not resolve all issues"
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v2
         with:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_OCEAN_0A5354E10 }}
-          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
           action: 'upload'
-          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
-          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
-          app_location: '/' # App source code path
-          api_location: '' # Api source code path - optional
-          output_location: 'build' # Built app content directory - optional
-          ###### End of Repository/Build Configurations ######
+          app_location: '/' 
+          api_location: '' 
+          output_location: 'build' 
 
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
@@ -42,7 +47,7 @@ jobs:
     steps:
       - name: Close Pull Request
         id: closepullrequest
-        uses: Azure/static-web-apps-deploy@v1
+        uses: Azure/static-web-apps-deploy@v2
         with:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_OCEAN_0A5354E10 }}
           action: 'close'
